spring.data.mongodb.uri=mongodb+srv://rsaha7650:rohan12345@cluster0.xirpt6k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
