spring.data.mongodb.uri=mongodb+srv://rsaha7650:rohan12345@cluster0.xirpt6k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Cluster0
spring.data.mongodb.auto-index-creation=true



Kafka settings commented for cloud deployment
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
##spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
##spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.value.default.type=net.engineer.journalApp.model.SentimentData
#
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.group-id=abc


#spring.data.redis.host=redis-10730.c275.us-east-1-4.ec2.redns.redis-cloud.com
#spring.data.redis.port=10730
#spring.data.redis.username=default
#spring.data.redis.password=4LatOiQrfdF9iii7B8LCf3ggn4xs25Pf
#spring.data.redis.ssl.enabled=false


spring.data.redis.host=redis-14811.c301.ap-south-1-1.ec2.redns.redis-cloud.com
spring.data.redis.port=14811
spring.data.redis.username=default
spring.data.redis.password=GXYNUL5WqJ2kMHaFtR3h68oAKI5EAdyU
spring.data.redis.ssl.enabled=false


spring.main.allow-circular-references=true
weather.api.key=19835ef432679021bd8cea4b150c2a72
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rsaha7650@gmail.com
spring.mail.password=sgiu vaqv exys anjz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true